#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 188708-web-01 18.209.180.80:80 check\n\tserver 188708-web-02 100.25.198.136:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart

